export const SUPPORTED_COINS = [
  "bitcoin",
  "ethereum",
  "solana",
  "xrp",
  "dogecoin",
  "cardano",
  "avalanche",
  "chainlink",
  "polkadot",
  "near",
  "litecoin",
  "stellar",
  "uniswap",
  "aave",
  "cosmos",
  "algorand",
  "vechain",
  "tron",
  "filecoin",
  "hedera-hashgraph",
  "shiba-inu",
  "pepe",
  "bonk",
  "dogwifcoin",
  "floki",
  "matic-network",
  "arbitrum",
  "optimism",
  "starknet",
  "maker",
  "curve-dao-token",
  "yearn-finance",
  "1inch",
  "pancakeswap-token",
  "injective-protocol",
  "sei-network",
  "sui",
  "aptos",
  "celestia",
  "fetch-ai",
  "render-token",
  "the-graph",
  "lido-dao",
  "rocket-pool",
  "thorchain",
  "osmosis",
  "akash-network",
  "kava",
  "band-protocol",
  "blur",
  "dydx",
  "gmx",
  "synthetix",
  "compound-governance-token",
  "frax-share",
  "convex-finance",
  "balancer",
  "loopring",
  "zcash",
  "monero",
  "dash",
  "neo",
  "iota",
  "waves",
  "qtum",
  "icon",
  "ontology",
  "zilliqa",
  "decred",
  "ravencoin",
  "horizen",
  "komodo",
  "stratis",
  "syscoin",
] as const;

export type CoinSlug = typeof SUPPORTED_COINS[number];

export const COIN_METADATA: Record<CoinSlug, { name: string; symbol: string; cgId: string }> = {
  bitcoin: { name: "Bitcoin", symbol: "BTC", cgId: "bitcoin" },
  ethereum: { name: "Ethereum", symbol: "ETH", cgId: "ethereum" },
  solana: { name: "Solana", symbol: "SOL", cgId: "solana" },
  xrp: { name: "XRP", symbol: "XRP", cgId: "ripple" },
  dogecoin: { name: "Dogecoin", symbol: "DOGE", cgId: "dogecoin" },
  cardano: { name: "Cardano", symbol: "ADA", cgId: "cardano" },
  avalanche: { name: "Avalanche", symbol: "AVAX", cgId: "avalanche-2" },
  chainlink: { name: "Chainlink", symbol: "LINK", cgId: "chainlink" },
  polkadot: { name: "Polkadot", symbol: "DOT", cgId: "polkadot" },
  near: { name: "NEAR Protocol", symbol: "NEAR", cgId: "near" },
  litecoin: { name: "Litecoin", symbol: "LTC", cgId: "litecoin" },
  stellar: { name: "Stellar", symbol: "XLM", cgId: "stellar" },
  uniswap: { name: "Uniswap", symbol: "UNI", cgId: "uniswap" },
  aave: { name: "Aave", symbol: "AAVE", cgId: "aave" },
  cosmos: { name: "Cosmos", symbol: "ATOM", cgId: "cosmos" },
  algorand: { name: "Algorand", symbol: "ALGO", cgId: "algorand" },
  vechain: { name: "VeChain", symbol: "VET", cgId: "vechain" },
  tron: { name: "TRON", symbol: "TRX", cgId: "tron" },
  filecoin: { name: "Filecoin", symbol: "FIL", cgId: "filecoin" },
  "hedera-hashgraph": { name: "Hedera", symbol: "HBAR", cgId: "hedera-hashgraph" },
  "shiba-inu": { name: "Shiba Inu", symbol: "SHIB", cgId: "shiba-inu" },
  pepe: { name: "Pepe", symbol: "PEPE", cgId: "pepe" },
  bonk: { name: "Bonk", symbol: "BONK", cgId: "bonk" },
  dogwifcoin: { name: "dogwifhat", symbol: "WIF", cgId: "dogwifcoin" },
  floki: { name: "FLOKI", symbol: "FLOKI", cgId: "floki" },
  "matic-network": { name: "Polygon", symbol: "MATIC", cgId: "matic-network" },
  arbitrum: { name: "Arbitrum", symbol: "ARB", cgId: "arbitrum" },
  optimism: { name: "Optimism", symbol: "OP", cgId: "optimism" },
  starknet: { name: "StarkNet", symbol: "STRK", cgId: "starknet" },
  maker: { name: "Maker", symbol: "MKR", cgId: "maker" },
  "curve-dao-token": { name: "Curve DAO", symbol: "CRV", cgId: "curve-dao-token" },
  "yearn-finance": { name: "Yearn Finance", symbol: "YFI", cgId: "yearn-finance" },
  "1inch": { name: "1inch", symbol: "1INCH", cgId: "1inch" },
  "pancakeswap-token": { name: "PancakeSwap", symbol: "CAKE", cgId: "pancakeswap-token" },
  "injective-protocol": { name: "Injective", symbol: "INJ", cgId: "injective-protocol" },
  "sei-network": { name: "Sei", symbol: "SEI", cgId: "sei-network" },
  sui: { name: "Sui", symbol: "SUI", cgId: "sui" },
  aptos: { name: "Aptos", symbol: "APT", cgId: "aptos" },
  celestia: { name: "Celestia", symbol: "TIA", cgId: "celestia" },
};

export const COIN_ANALYSIS: Record<CoinSlug, { tagline: string; pros: string[]; cons: string[]; analysis: string }> = {
  bitcoin: {
    tagline: "The original cryptocurrency and digital gold.",
    pros: ["Most liquid crypto asset", "Widely accepted globally", "Store of value narrative", "Institutional adoption growing"],
    cons: ["High price per coin (though fractional OK)", "Slower transaction speeds", "Energy intensive"],
    analysis: `Bitcoin (BTC) remains the gold standard of cryptocurrency. Created in 2009 by the pseudonymous Satoshi Nakamoto, Bitcoin pioneered decentralized digital currency and continues to dominate the market with the largest market cap of any cryptocurrency.\n\nAs a long-term investment, Bitcoin has historically outperformed most traditional assets, despite significant volatility. Institutional adoption from companies like MicroStrategy, Tesla, and major ETF issuers has legitimized BTC as a portfolio diversifier.\n\nFor retail investors, Bitcoin's "digital gold" narrative makes it a relatively straightforward long-term hold — particularly in times of inflation or currency debasement. Dollar-cost averaging (DCA) remains the most recommended strategy for new investors.\n\nBitcoin's fixed supply of 21 million coins, combined with halving events every ~4 years, creates a deflationary pressure that many analysts believe will drive long-term price appreciation. The approval of spot Bitcoin ETFs in 2024 opened the door for massive institutional inflows.`,
  },
  ethereum: {
    tagline: "The world's programmable blockchain.",
    pros: ["Largest DeFi and smart contract ecosystem", "Proof-of-Stake (energy efficient)", "ETH ETFs approved", "Active developer community"],
    cons: ["Gas fees can be high during congestion", "Competition from faster L1s", "Complex technical upgrades"],
    analysis: `Ethereum (ETH) is far more than just a currency — it's the backbone of decentralized finance, NFTs, and the broader Web3 ecosystem. As the second-largest cryptocurrency by market cap, Ethereum powers thousands of decentralized applications (dApps) and smart contracts.\n\nThe transition to Proof-of-Stake via "The Merge" in 2022 dramatically reduced Ethereum's energy consumption and introduced staking rewards, giving ETH holders a yield-bearing option. This makes ETH arguably more attractive as both a speculative asset and a productive one.\n\nFor investors, ETH's value is tied to the usage of its network. As DeFi, NFTs, and Layer 2 solutions continue to grow, demand for ETH increases. Layer 2 networks like Arbitrum and Optimism built on Ethereum further expand its utility without sacrificing security.\n\nThe approval of spot Ethereum ETFs further validates ETH as a mainstream investable asset. Many analysts consider ETH an "ultra-sound money" play given its deflationary tokenomics post-merge.`,
  },
  solana: {
    tagline: "High-performance blockchain built for speed and scale.",
    pros: ["Ultra-fast transactions (~65,000 TPS)", "Very low fees (<$0.01)", "Thriving NFT and DeFi ecosystem", "Strong developer growth"],
    cons: ["History of network outages", "More centralized than Bitcoin/Ethereum", "Younger ecosystem"],
    analysis: `Solana (SOL) has emerged as one of the most compelling alternatives to Ethereum, offering blazing-fast transaction speeds and near-zero fees. Originally launched in 2020, Solana quickly attracted developers building DeFi protocols, NFT marketplaces, and gaming applications.\n\nDespite facing significant challenges — including the FTX collapse which hit Solana hard — the network has demonstrated remarkable resilience. SOL recovered strongly in 2023-2024, driven by renewed developer interest, a booming NFT scene, and the explosive popularity of meme coins on the Solana network.\n\nFor traders, Solana offers a higher-risk, higher-reward profile compared to BTC or ETH. Its performance is closely tied to network adoption and the health of its DeFi ecosystem. Investors bullish on high-throughput blockchains and low-fee applications tend to favor SOL.\n\nSolana's improving infrastructure, reduced downtime, and growing institutional interest make it a serious contender as a top-tier blockchain platform for the next cycle.`,
  },
  xrp: {
    tagline: "Institutional cross-border payments at lightning speed.",
    pros: ["Extremely fast settlement (3-5 seconds)", "Very low fees", "Ripple's banking partnerships", "Legal clarity improving"],
    cons: ["Ongoing SEC regulatory history", "Centralization concerns", "Dependent on Ripple's business success"],
    analysis: `XRP is the native digital asset of the XRP Ledger (XRPL), designed primarily for fast, low-cost international money transfers. Unlike Bitcoin, XRP was created with financial institutions in mind — Ripple Labs has built extensive partnerships with banks and payment providers globally.\n\nThe long-running SEC vs. Ripple lawsuit cast a shadow over XRP for years, but the partial court victory in 2023 (XRP is not a security in programmatic sales) provided significant legal clarity. This triggered a major rally and renewed institutional interest.\n\nXRP processes transactions in 3-5 seconds with fees as low as fractions of a cent, making it one of the most practical cryptocurrencies for real-world payment use cases. Ripple's On-Demand Liquidity (ODL) product uses XRP as a bridge currency for cross-border payments.\n\nFor investors, XRP is a bet on the adoption of blockchain-based cross-border payments and Ripple's ability to onboard more financial institutions. It's a more speculative, narrative-driven investment compared to BTC or ETH.`,
  },
  dogecoin: {
    tagline: "The original meme coin with real-world utility.",
    pros: ["Large, loyal community", "Elon Musk association", "Low transaction fees", "Widely accepted by merchants"],
    cons: ["Inflationary supply (no hard cap)", "Primarily sentiment-driven", "Limited technical development"],
    analysis: `Dogecoin (DOGE) started as a joke in 2013 but has evolved into one of the most recognized cryptocurrency brands in the world. With Elon Musk as its unofficial spokesman and a devoted community nicknamed the "Doge Army," DOGE has proven its staying power through multiple market cycles.\n\nUnlike most cryptocurrencies, Dogecoin has an unlimited supply — 5 billion new DOGE are minted annually. This inflationary model means DOGE is better suited as a spending currency than a store of value, though sentiment-driven rallies can produce massive short-term gains.\n\nDogecoin has genuine utility: it's fast, cheap to transact, and accepted by a growing number of merchants including Tesla merchandise, some Newegg products, and various online services. The potential integration with X (formerly Twitter) for payments has been a recurring catalyst.\n\nFor investors, DOGE is a high-risk, sentiment-driven asset. Position sizing is key — many traders treat DOGE as a small speculative bet within a diversified crypto portfolio rather than a core holding.`,
  },
  cardano: {
    tagline: "The research-driven, peer-reviewed blockchain.",
    pros: ["Academic/peer-reviewed approach", "Proof-of-Stake from inception", "Growing African market focus", "Hydra scalability layer"],
    cons: ["Slow development pace historically", "Smaller DeFi ecosystem vs ETH/SOL", "Complex governance"],
    analysis: `Cardano (ADA) stands apart in the crypto space for its methodical, academic approach to blockchain development. Founded by Ethereum co-founder Charles Hoskinson, Cardano uses peer-reviewed research and formal verification to build a secure, scalable blockchain platform.\n\nCardano's development roadmap is divided into named eras (Byron, Shelley, Goguen, Basho, Voltaire), each adding new capabilities. The introduction of smart contracts via Plutus and the Alonzo hard fork enabled a growing DeFi ecosystem, though it remains smaller than Ethereum's or Solana's.\n\nOne unique aspect of Cardano is its focus on emerging markets — particularly Africa — where Cardano is being used for identity verification, land registry, and education credentialing in partnership with governments.\n\nFor investors, ADA is a long-term thesis play on Cardano's methodical development eventually delivering a highly scalable, formally verified blockchain. It requires patience but appeals to those who believe technical rigor matters in the long run.`,
  },
  avalanche: {
    tagline: "Blazing fast, low-cost, eco-friendly smart contracts.",
    pros: ["Sub-second finality", "EVM compatible (easy ETH migration)", "Subnet architecture for custom chains", "Strong institutional backing (Ava Labs)"],
    cons: ["Competition from Ethereum L2s", "Smaller ecosystem than ETH", "AVAX token utility dependent on subnet growth"],
    analysis: `Avalanche (AVAX) is a smart contract platform that achieves near-instant transaction finality through its innovative consensus mechanism. Unlike traditional blockchains, Avalanche uses a unique three-chain architecture — the X-Chain, C-Chain, and P-Chain — each optimized for different tasks.\n\nAvalanche's killer feature is its Subnet architecture, which allows anyone to create custom blockchain networks that inherit Avalanche's security. This has attracted institutions, gaming companies, and DeFi protocols looking to build their own chains without compromising on speed or security.\n\nAvalanche's C-Chain is fully EVM-compatible, making it easy for Ethereum developers to deploy existing smart contracts with minimal changes. This has enabled rapid ecosystem growth, with major DeFi protocols like Aave, Curve, and Trader Joe operating on the network.\n\nFor investors, AVAX is a bet on enterprise and institutional blockchain adoption via Subnets. Ava Labs has been aggressive in signing partnerships and the upcoming Avalanche9000 upgrade promises to dramatically reduce Subnet deployment costs, which could be a major catalyst.`,
  },
  chainlink: {
    tagline: "The decentralized oracle network powering DeFi.",
    pros: ["Dominant oracle market share (70%+)", "Critical infrastructure for all of DeFi", "CCIP enabling cross-chain growth", "Staking now live"],
    cons: ["Oracle services market has competitors", "LINK appreciation tied to network fees", "Less speculative upside than pure smart contract platforms"],
    analysis: `Chainlink (LINK) occupies a unique and critical position in the blockchain ecosystem — it's the leading decentralized oracle network that connects smart contracts to real-world data. Without oracles like Chainlink, DeFi protocols couldn't access price feeds, sports scores, weather data, or any off-chain information.\n\nWith over 70% market share in the oracle space, Chainlink has established itself as essential infrastructure for DeFi. Its data feeds are used by Aave, Compound, Synthetix, and hundreds of other protocols managing tens of billions in assets. LINK is the token used to pay oracle node operators.\n\nChainlink's Cross-Chain Interoperability Protocol (CCIP) is a newer product that enables secure communication between different blockchains — effectively positioning Chainlink as the "SWIFT" of blockchain interoperability. This significantly expands Chainlink's addressable market.\n\nFor investors, LINK is a "picks and shovels" play on DeFi growth — as the DeFi ecosystem expands, demand for reliable oracles grows with it. Chainlink staking, now live, provides additional utility and deflationary pressure on LINK's circulating supply.`,
  },
  polkadot: {
    tagline: "The blockchain of blockchains — interoperability at scale.",
    pros: ["Parachain architecture enables specialization", "Shared security model", "Cross-chain communication built in", "Strong developer grants program"],
    cons: ["Parachain slot auctions complex", "Competition from Cosmos, IBC", "Development pace slower than competitors"],
    analysis: `Polkadot (DOT) was built to solve one of blockchain's biggest challenges: interoperability. Founded by Ethereum co-founder Gavin Wood, Polkadot enables different blockchains (called parachains) to communicate and share security through its relay chain architecture.\n\nPolkadot's unique parachain model allows specialized blockchains to be built and deployed — each optimized for a specific use case (DeFi, NFTs, privacy, IoT) — while benefiting from Polkadot's shared security. This heterogeneous multi-chain architecture is distinct from both Ethereum and Cosmos.\n\nThe network has seen significant growth in its parachain ecosystem, with notable projects like Acala (DeFi), Moonbeam (EVM compatibility), and Astar (smart contracts) building on Polkadot. The recently launched Polkadot 2.0 aims to simplify the architecture and reduce friction for developers.\n\nFor investors, DOT is a long-term infrastructure bet on the multi-chain future of Web3. The staking yield (historically 10-15% APY) provides income while waiting for broader ecosystem adoption. However, Polkadot's complexity has been a barrier to entry for many retail users.`,
  },
  near: {
    tagline: "Developer-friendly blockchain built for mass adoption.",
    pros: ["Human-readable account names", "Sharding (Nightshade) for scalability", "Fast and cheap transactions", "Chain abstraction pioneering"],
    cons: ["Smaller ecosystem vs top competitors", "Less brand recognition", "Still building DeFi depth"],
    analysis: `NEAR Protocol (NEAR) is a developer-friendly, proof-of-stake blockchain designed with usability and scalability in mind. Founded in 2020, NEAR distinguishes itself through human-readable account names (e.g., "alice.near" instead of a hex address), making it far more approachable for mainstream users.\n\nNEAR's Nightshade sharding technology allows the network to scale horizontally — adding more shards as transaction volume grows — theoretically enabling unlimited throughput. This technical foundation makes NEAR well-positioned for mass-market applications.\n\nOne of NEAR's most exciting developments is chain abstraction — the concept of allowing users to interact with any blockchain from a NEAR account, without needing to manage multiple wallets or bridges. This could be transformative for mainstream crypto adoption.\n\nFor investors, NEAR is a higher-risk, higher-reward bet on a newer blockchain ecosystem that has strong technical fundamentals but hasn't yet achieved the network effects of ETH or SOL. The team's focus on chain abstraction and developer experience could drive significant growth as Web3 matures.`,
  },
  litecoin: { tagline: "The silver to Bitcoin's gold.", pros: ["Fast 2.5min block times", "Low fees", "Long track record since 2011", "Widely supported"], cons: ["Limited innovation", "Follows Bitcoin price", "No smart contracts"], analysis: "Litecoin (LTC) is one of the oldest cryptocurrencies, created in 2011 as a faster, lighter Bitcoin. With 2.5 minute block times and minimal fees, it remains a reliable payments-focused crypto. Its long track record and widespread exchange support make it a staple in diversified portfolios." },
  stellar: { tagline: "Cross-border payments for the unbanked.", pros: ["5-second settlement", "Near-zero fees", "Focus on financial inclusion", "IBM partnership history"], cons: ["Competing with XRP in same niche", "Centralization concerns", "Slower ecosystem growth"], analysis: "Stellar (XLM) is a payments-focused blockchain for cross-border transfers and financial inclusion, co-founded by Jed McCaleb. Its network enables near-instant, near-free transactions and has partnerships with major institutions for remittance corridors globally." },
  uniswap: { tagline: "The leading decentralized exchange protocol.", pros: ["Dominant DEX by volume", "Permissionless token listing", "UNI governance token", "V4 bringing upgrades"], cons: ["Impermanent loss risk for LPs", "Competition from other DEXs", "Regulatory scrutiny"], analysis: "Uniswap (UNI) is the largest decentralized exchange by volume, enabling permissionless token swaps across Ethereum and major L2s. UNI grants governance rights over the protocol treasury. As DeFi grows, Uniswap's position as the default swap protocol underpins UNI's long-term value." },
  aave: { tagline: "The leading decentralized lending protocol.", pros: ["Billions in TVL", "Flash loans", "AAVE safety module staking", "GHO stablecoin"], cons: ["Smart contract risk", "Liquidation risk", "Complex for new users"], analysis: "Aave (AAVE) is the premier decentralized lending protocol enabling crypto-collateralized loans and yield on deposits. Aave pioneered flash loans and operates across Ethereum, Polygon, Avalanche and others. AAVE staking secures the protocol and earns rewards." },
  cosmos: { tagline: "The internet of blockchains.", pros: ["IBC cross-chain communication", "Thriving app-chain ecosystem", "ATOM staking rewards", "Proven Tendermint consensus"], cons: ["ATOM value accrual debated", "Competition from Polkadot", "Complex ecosystem"], analysis: "Cosmos (ATOM) connects sovereign blockchains via the IBC protocol. Its ecosystem hosts dYdX, Osmosis, Celestia and hundreds of app-chains. ATOM secures the Cosmos Hub and earns staking rewards, positioning it as a reserve asset for the interchain economy." },
  algorand: { tagline: "Pure proof-of-stake for the borderless economy.", pros: ["Instant finality", "Carbon-neutral", "MIT-founded academic roots", "TradFi integration focus"], cons: ["Smaller ecosystem", "Underperformed historically", "Stiff competition"], analysis: "Algorand (ALGO) was founded by MIT cryptographer Silvio Micali and achieves instant transaction finality via Pure PoS. It targets traditional finance integration including CBDCs and securities tokenization, making it one of the most institutionally credible blockchains." },
  vechain: { tagline: "Enterprise blockchain for supply chain and sustainability.", pros: ["Real enterprise partnerships (Walmart China, BMW)", "Dual-token model (VET/VTHO)", "ESG focus", "Proven use cases"], cons: ["Slow enterprise sales cycles", "Less DeFi activity", "Partnership dependent"], analysis: "VeChain (VET) is an enterprise blockchain for supply chain management and sustainability, with real deployments at Walmart China, BMW, and DNV. Its dual-token model keeps gas costs (VTHO) predictable for businesses while VET captures value appreciation." },
  tron: { tagline: "High-throughput blockchain dominating stablecoin transfers.", pros: ["Massive USDT volume", "Near-zero fees", "High TPS", "Aggressive ecosystem growth"], cons: ["Centralization concerns", "Controversial founder", "Reputation issues in Western markets"], analysis: "TRON (TRX) has become the dominant network for USDT stablecoin transfers globally, processing billions in daily volume with near-zero fees. Despite controversies around founder Justin Sun, TRON's utility for stablecoin remittances keeps it among the most-used blockchains by transaction count." },
  filecoin: { tagline: "Decentralized storage for the open web.", pros: ["Largest decentralized storage network", "FIL staking for providers", "IPFS integration", "Growing Web3 demand"], cons: ["Complex tokenomics", "Storage market competition", "Volatile price"], analysis: "Filecoin (FIL) is the leading decentralized storage network built on IPFS. Providers earn FIL by offering storage capacity while users pay to store data. As Web3 infrastructure and demand for censorship-resistant storage grows, Filecoin's network effects position it as the dominant decentralized storage layer." },
  "hedera-hashgraph": { tagline: "Enterprise-grade public ledger using hashgraph consensus.", pros: ["Fortune 500 governance council", "High throughput and fairness", "Low predictable fees", "Carbon-negative"], cons: ["Patented technology limits forks", "Centralized governance", "Less crypto-native community"], analysis: "Hedera (HBAR) uses hashgraph consensus governed by a council including Google, IBM, and Boeing. It achieves high throughput with mathematically proven fairness and is carbon-negative. HBAR is growing in enterprise tokenization, payments, and sustainability tracking applications." },
  "shiba-inu": { tagline: "The Dogecoin killer turned DeFi ecosystem.", pros: ["Massive SHIB Army community", "ShibaSwap DEX", "Shibarium L2", "Burn mechanism"], cons: ["Quadrillions of tokens in supply", "Primarily sentiment-driven", "Extreme volatility"], analysis: "Shiba Inu (SHIB) evolved from a Dogecoin competitor into a broader ecosystem with ShibaSwap DEX, Shibarium Layer 2, and BONE/LEASH sister tokens. The SHIB Army community is one of crypto's most active, and ongoing token burns gradually reduce the massive supply." },
  pepe: { tagline: "The king of meme coins on Ethereum.", pros: ["Iconic meme culture resonance", "Top 20 market cap", "Massive volume and community", "No transfer tax"], cons: ["Zero utility", "Extreme volatility", "No development roadmap"], analysis: "Pepe (PEPE) is a meme coin based on the iconic Pepe the Frog internet meme. Launched in 2023, it rapidly became a top-20 cryptocurrency by market cap on community enthusiasm alone. PEPE is a pure speculation play during crypto bull markets — high risk, potentially high reward." },
  bonk: { tagline: "Solana's first major meme coin.", pros: ["Solana ecosystem integration", "Airdropped to community", "Major exchange listings", "Supply burns"], cons: ["Pure speculation", "Solana dependent", "High volatility"], analysis: "Bonk (BONK) was airdropped to Solana NFT holders in late 2022 to revive ecosystem morale post-FTX. It became the first major Solana meme coin and helped restart Solana's NFT and DeFi ecosystem. BONK is integrated across Solana DeFi platforms and accepted by various protocols as payment." },
  dogwifcoin: { tagline: "The dog with a hat that took crypto by storm.", pros: ["Top meme coin by market cap", "Strong community", "Viral concept", "Solana-native"], cons: ["No utility", "Extreme volatility", "Entirely sentiment driven"], analysis: "Dogwifhat (WIF) is a Solana meme coin featuring a Shiba Inu wearing a pink hat. Launched late 2023, it exploded to billions in market cap in early 2024. Like all meme coins, WIF is purely speculative and best treated as a small fun allocation within a diversified crypto portfolio." },
  floki: { tagline: "The meme coin with a utility ecosystem.", pros: ["Valhalla metaverse game", "FlokiFi DeFi suite", "Strong marketing", "Cross-chain (ETH + BNB)"], cons: ["Execution risk on roadmap", "Meme coin volatility", "Heavy competition"], analysis: "FLOKI is a meme coin inspired by Elon Musk's dog that has built an ecosystem including Valhalla (a play-to-earn game) and FlokiFi (DeFi tools). Unlike pure meme coins, FLOKI invests in product development and operates on both Ethereum and BNB Chain, giving it more utility than most meme tokens." },
  "matic-network": { tagline: "Ethereum's leading Layer 2 scaling solution.", pros: ["Massive developer adoption", "EVM compatible", "Polygon 2.0 zkEVM", "Major brand partnerships"], cons: ["Intense L2 competition", "Token migration complexity", "Fee pressure"], analysis: "Polygon (MATIC/POL) is one of Ethereum's most successful scaling solutions with major enterprise partnerships including Reddit, Starbucks, and Nike. Polygon 2.0 transitions to a ZK-powered network of chains. Its ecosystem size and brand recognition give it staying power despite growing L2 competition." },
  arbitrum: { tagline: "The leading Ethereum Layer 2 by TVL.", pros: ["Largest L2 TVL", "EVM compatible", "Stylus enables Rust contracts", "Strong DeFi ecosystem"], cons: ["ARB limited value accrual", "Centralized sequencer", "L2 competition"], analysis: "Arbitrum (ARB) is the Ethereum Layer 2 with the largest total value locked, using optimistic rollups for cheap Ethereum-compatible transactions. Major DeFi protocols like GMX, Uniswap, and Aave have significant Arbitrum deployments. ARB governs the Arbitrum DAO and its substantial ecosystem treasury." },
  optimism: { tagline: "Ethereum L2 powering the Superchain vision.", pros: ["OP Stack powers Base and other chains", "Retroactive public goods funding", "Strong ecosystem", "EVM equivalent"], cons: ["OP value accrual developing", "Fraud proof delays", "Superchain competition"], analysis: "Optimism (OP) is an Ethereum L2 and architect of the Superchain — a network of OP Stack chains including Coinbase's Base. OP governs the Optimism Collective and funds public goods via retroactive grants. The Superchain vision could make OP Stack the dominant L2 framework across the industry." },
  starknet: { tagline: "Zero-knowledge Ethereum L2 with Cairo smart contracts.", pros: ["ZK proofs superior security", "STARK proofs scale without trusted setup", "Native account abstraction", "Growing gaming and DeFi ecosystem"], cons: ["Cairo learning curve", "Smaller than Arbitrum/Optimism", "Token distribution controversies"], analysis: "StarkNet (STRK) uses STARK cryptographic proofs for Ethereum scalability, providing instant mathematical validity without waiting periods. Native account abstraction enables better UX. StarkNet is gaining traction in gaming and DeFi as ZK technology matures and developer tooling improves." },
  maker: { tagline: "The protocol behind DAI, DeFi's most battle-tested stablecoin.", pros: ["DAI is most decentralized major stablecoin", "Billions in collateral", "MKR burned from fees", "Sky expansion"], cons: ["Slow MKR burn rate", "Regulatory risk on stablecoins", "Complex system"], analysis: "Maker (MKR) governs the MakerDAO protocol creating DAI, the most decentralized major stablecoin backed by crypto collateral. Protocol fees buy and burn MKR creating deflationary pressure. The Sky rebrand expands Maker's ambitions into a broader decentralized financial ecosystem." },
  "curve-dao-token": { tagline: "The backbone of DeFi stablecoin liquidity.", pros: ["Dominant stablecoin DEX", "CRV emissions drive liquidity wars", "veCRV vote-escrow model", "crvUSD stablecoin"], cons: ["Complex veTokenomics", "Founder exploit damaged trust", "Newer stable AMM competition"], analysis: "Curve (CRV) is the largest DEX for stablecoin swaps, underpinning DeFi's liquidity infrastructure. The Curve Wars — protocols competing for CRV emissions — made CRV one of DeFi's most influential tokens. Its veCRV tokenomics model has been widely copied across the ecosystem." },
  "yearn-finance": { tagline: "Automated DeFi yield optimization.", pros: ["Pioneered yield farming automation", "Ultra-scarce supply (36,666 YFI)", "Vaults auto-compound", "Strong developer culture"], cons: ["YFI highly volatile", "Strategy complexity", "Smart contract risk"], analysis: "Yearn Finance (YFI) is a DeFi yield aggregator automatically moving funds between protocols to maximize returns. YFI became legendary in 2020 distributing tokens with no VC allocation. Its ultra-scarce supply and active vault development keep it relevant as a high-conviction DeFi blue chip." },
  "1inch": { tagline: "The leading DEX aggregator for best swap prices.", pros: ["Aggregates 300+ DEXs", "Pathfinder finds best rates", "1INCH staking", "Fusion gasless swaps"], cons: ["Thin aggregator margins", "Competition from other aggregators", "Revenue model developing"], analysis: "1inch (1INCH) splits trades across hundreds of DEXs to find the best available price. Aggregating Uniswap, Curve, Balancer and more, 1inch saves traders significant slippage on large orders. Fusion mode enables gasless swaps using resolvers who compete to fill orders at best prices." },
  "pancakeswap-token": { tagline: "BNB Chain's leading DEX and yield farm.", pros: ["Dominant on BNB Chain", "Very low fees", "Lottery, prediction, NFTs", "CAKE burns"], cons: ["BNB Chain dependent", "DEX competition", "Historical inflation"], analysis: "PancakeSwap (CAKE) is BNB Chain's leading DEX offering swaps, yield farming, staking, NFTs, and prediction markets. With low fees and a large Asian user base, PancakeSwap is the Uniswap of BNB Chain. Revised tokenomics added deflationary CAKE burns to reduce inflation over time." },
  "injective-protocol": { tagline: "The blockchain built for finance.", pros: ["Built for financial apps", "Native orderbook DEX", "Cosmos IBC connected", "Fast finality"], cons: ["Newer ecosystem", "Finance chain competition", "Less liquidity than ETH DeFi"], analysis: "Injective (INJ) is a layer-1 blockchain purpose-built for DeFi with a native on-chain orderbook enabling fast derivatives and spot trading. Built on Cosmos with IBC connectivity, INJ staking provides security rewards and governance rights. Multiple DeFi protocols focused on perpetuals and futures have deployed on Injective." },
  "sei-network": { tagline: "The fastest layer 1 blockchain for trading.", pros: ["Native orderbook for trading", "Twin-turbo consensus", "Parallelized EVM in V2", "Sub-second finality"], cons: ["Young ecosystem", "Focused scope may limit general DeFi", "L1 competition"], analysis: "Sei (SEI) is a Cosmos-based layer-1 optimized for trading with a built-in orderbook matching engine. Sei V2 introduces parallelized EVM execution for Ethereum-compatible contracts with Sei's performance. The chain targets DEXs and latency-sensitive DeFi applications requiring high throughput and low latency." },
  sui: { tagline: "Next-gen blockchain with object-oriented architecture.", pros: ["Move language prevents exploits", "Parallel transaction execution", "Strong gaming ecosystem", "Fast finality"], cons: ["Young ecosystem", "Token distribution concerns", "New L1 competition"], analysis: "Sui (SUI) was developed by Mysten Labs (ex-Meta/Diem) using the Move language. Its object-centric data model enables parallel execution of non-conflicting transactions. Sui has attracted significant gaming and consumer app development and offers staking yield for network participation." },
  aptos: { tagline: "The safest and most production-ready L1.", pros: ["Move language formal verification", "Block-STM parallel execution", "Strong VC backing", "Growing DeFi"], cons: ["Controversial token distribution", "Competing with Sui", "Less retail attention"], analysis: "Aptos (APT) was built by ex-Meta/Diem engineers using Move for formal verification of smart contracts. Block-STM parallel execution delivers high throughput. Despite a controversial launch, Aptos has built a growing DeFi ecosystem with backing from a16z, Binance Labs, and other top VCs." },
  celestia: { tagline: "The first modular data availability network.", pros: ["Pioneer of modular blockchain architecture", "Data availability sampling", "Powers many rollup ecosystems", "Strong academic backing"], cons: ["Abstract concept for retail", "TIA value accrual developing", "Very new technology"], analysis: "Celestia (TIA) separates data availability from execution and consensus, enabling rollups to scale massively by outsourcing data availability to Celestia. TIA is staked to secure the network and paid for blob data. Celestia represents the cutting edge of blockchain architecture and is foundational infrastructure for next-generation rollups." },
};